name: ci

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  yarn:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        node-version:
          - 14

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install node dependencies
        run: yarn install --frozen-lockfile

      - name: Install direnv
        run: |
          case "$RUNNER_OS" in
          macOs) brew install direnv ;;
          Linux) sudo apt-get install --yes direnv ;;
          esac

      - name: Test
        run: |
          case "$RUNNER_OS" in
          macOs) yarn run test ;;
          Linux) xvfb-run -a yarn run test ;;
          esac
