name: Test extension

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install direnv
        run: |
          case "$RUNNER_OS" in
          macOs) brew install direnv ;;
          Linux) sudo apt-get install --yes direnv ;;
          esac

      - name: Test
        run: |
          case "$RUNNER_OS" in
          macOs) npm test ;;
          Linux) xvfb-run -a npm test ;;
          esac
